GET http://localhost:8080/tasks/
Accept: */*
Cache-Control: no-cache
Content-Type: application/json;charset=UTF-8


### registers a new user
POST http://localhost:8080/users/sign-up
Accept: */*
Cache-Control: no-cache
Content-Type: application/json;charset=UTF-8

{ "username": "admin", "password": "password"}


### logs into the application (JWT is generated)

POST http://localhost:8080/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/json;charset=UTF-8

{ "username": "admin", "password": "password"}

###

GET http://localhost:8080/tasks/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTUyNDE5ODYzNH0.9eoHuelIzXQNcoQ1pEndLZFPgauWPYJqbKDkaCRxxPSqgha72sq6aDygeE565Yogv7m6OknNS2mMaD51AqztOQ
